project:
  type: website
  output-dir: docs

website:
  page-navigation: true
  title: "Nikolas P. Johnston"
  description: "Homepage for N Johnston CPD."
  site-url: "https://nikolasjohnston.github.io/johnston_cpd/"

  repo-url: https://github.com/nikolasjohnston/johnston_cpd
  repo-actions: [edit, issue]
  
  open-graph: true

  page-footer:
    right: "This page is built with [Quarto](https://quarto.org/)."
    left: "&copy; Copyright 2026, Nikolas Johnston"
    background: primary

  navbar: 
    background: primary
    search: true
    pinned: true
    left:
      - text: "Home"
        href: index.qmd


format:
  html:
    theme:
      light: [journal]
      dark: [journal, 'theme-dark.scss']
    code-copy: true
    code-overflow: wrap
    toc: true
freeze: auto

editor: visual

